### ISSUE TITLE
@conda-forge-admin, please add user @trey-stafford

### ISSUE THREAD

**Issue by mfisher87** [conda-forge/pangeo-forge-runner-feedstock#21]

**Comment by mfisher87** [comment]
@trey-stafford can you please confirm here you're willing to be a recipe maintainer and then we'll merge in the change :)

**Comment by weiji14** [comment]
Pinging @trey-stafford again. If we don't hear back in 1 month (until Dec 15), I'll close this issue and the associated PR.

**Comment by trey-stafford** [comment]
@weiji14 yes, confirmed that I'm willing to be a recipe maintainer. 

Apologies for not responding sooner - this one dropped off my TODO list somehow!

**Comment by weiji14** [comment]
No worries, I'm just going through my conda-forge backlog and cleaning up some issues/PRs. Have merged the PR at #22 now so you should get an email about it soon 😄
