### ISSUE TITLE
@conda-forge-admin, please add user @rushirajnenuji

### ISSUE THREAD

**Issue by mfisher87** [conda-forge/pangeo-forge-runner-feedstock#23]

**Comment by mfisher87** [comment]
@rushirajnenuji can you please comment here confirming you're willing to be a recipe maintainer and then we'll merge in the change :)

**Comment by rushirajnenuji** [comment]
Yes, I'm happy to confirm that I'm willing to be a recipe maintainer. Thank you @mfisher87 for setting up this request.
